db:
  host: localhost
  root: change-me-together-thick-music-moon
  port: 8529
  user: hello-world
  pass: change-me-voice-event-type-steel
auth:
  dpv_secret_key: 8K3KNYCjvJkLrg2oIJSfCVbU6iiqVEddTeC8-fi86WY
  # https://generate.plus/en/base64, 32, url-safe
  # used for replacing login tokens
  dpv_token_seconds: 3600
  facebook_graph_url: https://graph.facebook.com/debug_token
  facebook_app_id: 448535201950
  google_client_id: 123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com
  google_client_secret: GOCSBX-abcdefghijklmnopqrstuvwxyz
  deepl_key: 12345678-1234-1234-1234-123456789012:fz
  deepl_url: https://api-free.deepl.com/v2/translate
  minecraft_invite_key: minecraft-is-full-of-joy
nextcloud:
  url: https://share.parkour-deutschland.de/
  user: dpv
  pass: ABCDE-FGHIJ-KLMNO-PQRST-UVWXY
  formId: 1234567890
server:
  words1: words1.example.txt
  words2: words2.example.txt
  img_url: /obj/dpv/img
  tmp_url: /obj/dpv/tmp
  img_path: /var/www/8bj/obj/dpv/img
  tmp_path: /var/www/8bj/obj/dpv/tmp
  exiftool: exiftool
  python: python3
  account: /var/dpv/account.json
settings:
  languages:
    - key: "de"
      name: Deutsch
      icon: ğŸ‡©ğŸ‡ª
    - key: "en"
      name: English
      icon: ğŸ‡¬ğŸ‡§
    - key: "zh"
      name: ä¸­æ–‡
      icon: ğŸ‡¨ğŸ‡³
    - key: "ru"
      name: Ğ ÑƒÑÑĞºĞ¸Ğ¹
      icon: ğŸ‡·ğŸ‡º
    - key: "es"
      name: EspaÃ±ol
      icon: ğŸ‡ªğŸ‡¸
    - key: "fr"
      name: FranÃ§ais
      icon: ğŸ‡«ğŸ‡·
    - key: "it"
      name: Italiano
      icon: ğŸ‡®ğŸ‡¹
    - key: "nl"
      name: Nederlands
      icon: ğŸ‡³ğŸ‡±
    - key: "pt"
      name: PortuguÃªs
      icon: ğŸ‡µğŸ‡¹
    - key: "sv"
      name: Svenska
      icon: ğŸ‡¸ğŸ‡ª
    - key: "no"
      name: Norsk
      icon: ğŸ‡³ğŸ‡´
    - key: "fi"
      name: Suomi
      icon: ğŸ‡«ğŸ‡®
  user_types:
    - user
    - athlete
    - coach
    - team
    - group
    - association
    - freelancer
    - company
    - school
    - government
